import Head from "next/head"
import { Inter } from "next/font/google"
import Hero from "../../components/Hero"
import Categories from "../../components/Categories"
import FeaturedProducts from "../../components/FeaturedProducts"
import axios from "axios"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ featuredProducts }) {
  return (
    <>
      <Head>
        <title>Next-JS Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-1.ico" />
      </Head>
      <>
        <Hero />
        <Categories />
        <FeaturedProducts products={featuredProducts} />
      </>
    </>
  )
}

export async function getServerSideProps() {
  const { data } = await axios.get(
    // `https://ecommerce-next-js-xz5u.vercel.app//api/products`
    `${process.env.NEXT_PUBLIC_APP_URL}/api/products`
  )

  return {
    props: {
      featuredProducts: data,
    },
  }
}

/*
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'
import Categories from '../../components/Categories'
import FeaturedProducts from '../../components/FeaturedProducts'
import Footer from '../../components/Footer'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ featuredProducts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <Navbar />
      <Hero />
      <Categories />
      <FeaturedProducts products={featuredProducts} />
      <Footer />
      </>
    </>
  )
}


export async function getServerSideProps(){
  const { data } = await axios.get(`https://ecommerce-next-js-xz5u.vercel.app//api/products`)

  return {
    props: {
      featuredProducts: data
    }
  }
}
*/
